### ISSUE TITLE
Got problems deploying prometheus....

### ISSUE THREAD

**Issue by mrmyiagi2018** [mindsphere/devops-demo#1]
Hi,
I tried to deploy prometheus in MindSphere using your instructions but got an error during pushing...

   -----> Running: go install -tags cloudfoundry -buildmode pie github.com/prometheus/prometheus/cmd/prometheus
   can't load package: package github.com/prometheus/prometheus/cmd/prometheus: cannot find package "github.com/prometheus/prometheus/cmd/prometheus" in any of:
        /tmp/contents387928455/deps/0/go1.10.4/go/src/github.com/prometheus/prometheus/cmd/prometheus (from $GOROOT)
        /tmp/gobuildpack.gopath069963564/.go/src/github.com/prometheus/prometheus/cmd/prometheus (from $GOPATH)
          **ERROR** Unable to compile application: exit status 1
   Failed to compile droplet: Failed to run finalize script: exit status 12

Can you take a look at it? It seems that it's not the right path, isn't it? 
Besides i asked myself if the path in the manifest.yml is correct:  --config.file=./mindsphere-conf/prometheus.yml.... Shouldn't it be just the conf folder instead the mindsphere-conf?

Thanks!

**Comment by bufferoverflow** [comment]
could you please provide some more details such as steps executed successfully as described here https://gitlab.com/mindsphere/devops-demo/blob/master/devops/prometheus/README.md ?

and please file an issue over here https://gitlab.com/mindsphere/devops-demo/issues , GitHub is just a mirror
